":h set
":h option-list
se tf
se nu
se ts=4 sts=4 sw=4 et sta ai cin sw=4
se hls is ic
se sb sr
se cul

":h highlight
hi CursorLine cterm=NONE ctermbg=LightGrey ctermfg=None

":h no
no <c-k> <c-w>

":h nn
nn <cr> :noh<cr><cr>

":h syntax
sy on

":h grepprg
se gp=grep\ --color=always\ -n\ $*\ /dev/null

":h laststatus
se ls=0

":h wrap
se nowrap

