":h set
":h option-list
se tf
se nu
se ts=4 sts=4 sw=4 et sta ai cin sw=4
se hls is ic
se sb sr
se cul

":h highlight
se cursorlineopt=line
hi CursorLine cterm=NONE ctermbg=LightGrey ctermfg=None

":h no
no <c-k> <c-w>

":h nn
nn <cr> :noh<cr><cr>

":h syntax
sy on

":h grepprg
se gp=grep\ --color=always\ -n\ $*\ /dev/null

":h laststatus
se ls=1

":h wrap
se nowrap

":h autocmd
au BufWritePre * %s/\s\+$//e

":h noswapfile
se noswapfile

":h path
se path+=/Library/Developer/CommandLineTools/usr/include/c++/v1
se path+=/usr/local/include

